/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author maria
 */
public class GUILose extends javax.swing.JFrame {

    /**
     * Creates new form GUILose
     */
    public GUILose() {
        initComponents();
        setLocationRelativeTo(null);//para poner la ventana al centro 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnRepetir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        imgLose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(851, 664));
        setMinimumSize(new java.awt.Dimension(851, 664));
        setSize(new java.awt.Dimension(851, 664));
        getContentPane().setLayout(null);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(580, 150, 80, 60);
        btnSalir.getAccessibleContext().setAccessibleName("btnSalir");

        btnRepetir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.png"))); // NOI18N
        btnRepetir.setBorderPainted(false);
        btnRepetir.setContentAreaFilled(false);
        btnRepetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepetirActionPerformed(evt);
            }
        });
        getContentPane().add(btnRepetir);
        btnRepetir.setBounds(330, 480, 190, 90);
        btnRepetir.getAccessibleContext().setAccessibleName("btnRepetir");

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volverPrin.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(650, 540, 150, 70);
        btnVolver.getAccessibleContext().setAccessibleName("btnVolver");

        imgLose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lose.png"))); // NOI18N
        imgLose.setText("jLabel1");
        getContentPane().add(imgLose);
        imgLose.setBounds(0, 0, 851, 664);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Crea una nueva instancia del JFrame
        GUISalir guiSalir = new GUISalir();

        // Establece visible la nueva ventana
        guiSalir.setVisible(true);

        // Cierra la ventana actual
        this.dispose();
        //o Oculta la ventana
        // Oculta la ventana actual en lugar de cerrarla
        //this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRepetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepetirActionPerformed
        // Crea una nueva instancia del JFrame
        GUILaberinto guiLaberinto = new GUILaberinto();
        
        // Cierra todas las ventanas activas excepto la nueva
        java.awt.Window[] windows = java.awt.Window.getWindows();
        for (java.awt.Window window : windows) {
            if (window.isVisible() && window != guiLaberinto) {
                window.dispose();
            }
        }

        // Establece visible la nueva ventana
        guiLaberinto.setVisible(true);
    }//GEN-LAST:event_btnRepetirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Crea una nueva instancia del JFrame
        GUIPrincipal guiPrincipal = new GUIPrincipal();

        // Cierra todas las ventanas activas excepto la nueva
        java.awt.Window[] windows = java.awt.Window.getWindows();
        for (java.awt.Window window : windows) {
            if (window.isVisible() && window != guiPrincipal) {
                window.dispose();
            }
        }

        // Establece visible la nueva ventana
        guiPrincipal.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUILose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUILose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUILose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUILose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUILose().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRepetir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel imgLose;
    // End of variables declaration//GEN-END:variables
}
