/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

public class GUISalir extends javax.swing.JFrame {

    /**
     * Creates new form GUISalir
     */
    public GUISalir() {
        initComponents();
        setLocationRelativeTo(null);//poner la posicion de la ventana al centro 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        imgFondoSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(866, 664));
        setMinimumSize(new java.awt.Dimension(866, 664));
        setResizable(false);
        setSize(new java.awt.Dimension(866, 664));
        getContentPane().setLayout(null);

        btnYes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yes.png"))); // NOI18N
        btnYes.setBorderPainted(false);
        btnYes.setContentAreaFilled(false);
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });
        getContentPane().add(btnYes);
        btnYes.setBounds(350, 290, 180, 70);
        btnYes.getAccessibleContext().setAccessibleName("btnYes");

        btnNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/no.png"))); // NOI18N
        btnNo.setBorderPainted(false);
        btnNo.setContentAreaFilled(false);
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNo);
        btnNo.setBounds(580, 290, 180, 70);
        btnNo.getAccessibleContext().setAccessibleName("btnNo");

        imgFondoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guiSalir.png"))); // NOI18N
        getContentPane().add(imgFondoSalir);
        imgFondoSalir.setBounds(0, 0, 866, 660);
        imgFondoSalir.getAccessibleContext().setAccessibleName("imgFondoSalir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnYesActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // Crea una nueva instancia del JFrame
        GUILaberinto guiLaberinto = new GUILaberinto();

        // Cierra todas las ventanas activas excepto la nueva
        java.awt.Window[] windows = java.awt.Window.getWindows();
        for (java.awt.Window window : windows) {
            if (window.isVisible() && window != guiLaberinto) {
                window.dispose();
            }
        }

        // Establece visible la nueva ventana
        guiLaberinto.setVisible(true);
    }//GEN-LAST:event_btnNoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUISalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUISalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUISalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUISalir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUISalir().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel imgFondoSalir;
    // End of variables declaration//GEN-END:variables
}
