/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

public class GUIWin extends javax.swing.JFrame {

    /**
     * Creates new form GUIWin
     */
    public GUIWin() {
        initComponents();
        setLocationRelativeTo(null);//para localizar la posicion de la ventana al centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        imgCompleto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(851, 664));
        setMinimumSize(new java.awt.Dimension(851, 664));
        setPreferredSize(new java.awt.Dimension(851, 664));
        setResizable(false);
        setSize(new java.awt.Dimension(851, 664));
        getContentPane().setLayout(null);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(330, 480, 200, 80);
        btnVolver.getAccessibleContext().setAccessibleName("btnVolver");

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btnSalir.setText("jButton2");
        btnSalir.setActionCommand("");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir);
        btnSalir.setBounds(580, 140, 75, 70);

        imgCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win.png"))); // NOI18N
        imgCompleto.setText("jLabel1");
        imgCompleto.setMaximumSize(new java.awt.Dimension(851, 664));
        imgCompleto.setMinimumSize(new java.awt.Dimension(851, 664));
        imgCompleto.setPreferredSize(new java.awt.Dimension(851, 664));
        getContentPane().add(imgCompleto);
        imgCompleto.setBounds(0, 0, 860, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Crea una nueva instancia del JFrame
        GUIPrincipal guiPrincipal = new GUIPrincipal();

        // Cierra todas las ventanas activas excepto la nueva
        java.awt.Window[] windows = java.awt.Window.getWindows();
        for (java.awt.Window window : windows) {
            if (window.isVisible() && window != guiPrincipal) {
                window.dispose();
            }
        }

        // Establece visible la nueva ventana
        guiPrincipal.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed
 private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Crea una nueva instancia del JFrame
        GUISalir guiSalir = new GUISalir();

        // Cierra todas las ventanas activas excepto la nueva
        java.awt.Window[] windows = java.awt.Window.getWindows();
        for (java.awt.Window window : windows) {
            if (window.isVisible() && window != guiSalir) {
                window.dispose();
            }
        }

        // Establece visible la nueva ventana
        guiSalir.setVisible(true);
    }        
         
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIWin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel imgCompleto;
    // End of variables declaration//GEN-END:variables
}
