/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ControladorPrincipal;

/**
 *
 * @author ramir
 */
public class GUIIntrucciones extends javax.swing.JFrame {

    /**
     * Creates new form GUIIntrucciones
     * @param controlador
     */
    public GUIIntrucciones(ControladorPrincipal controlador) {
        initComponents(); 
        
        escucharCerrar(controlador);//para controlar el boton: btnXCerrar
        
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
        
        setVisible(false);

    }

    public void escucharCerrar(ControladorPrincipal controlador){
       btnXCerrar.addActionListener(controlador);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXCerrar = new javax.swing.JButton();
        fondoInstrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnXCerrar.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        btnXCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btnXCerrar.setText("btnXCerrar");
        btnXCerrar.setBorderPainted(false);
        btnXCerrar.setContentAreaFilled(false);
        btnXCerrar.setIconTextGap(1);
        getContentPane().add(btnXCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 50, 50));

        fondoInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instructions.jpg"))); // NOI18N
        fondoInstrucciones.setText("jLabel1");
        getContentPane().add(fondoInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXCerrar;
    private javax.swing.JLabel fondoInstrucciones;
    // End of variables declaration//GEN-END:variables
}
