/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ramir
 */
public class GUILose extends javax.swing.JFrame {

    /**
     * Creates new form JuegoPerdido
     */
    public GUILose(Controller.ControladorPrincipal controlador) {
        initComponents();
        
         setLocationRelativeTo(null); // Centrar la ventana en la pantalla
         
          setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRepetir = new javax.swing.JButton();
        lose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRepetir.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        btnRepetir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.png"))); // NOI18N
        btnRepetir.setText("btnRepetir");
        btnRepetir.setContentAreaFilled(false);
        getContentPane().add(btnRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 190, -1));

        lose.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        lose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lose.png"))); // NOI18N
        lose.setText("jLabel1");
        getContentPane().add(lose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRepetir;
    private javax.swing.JLabel lose;
    // End of variables declaration//GEN-END:variables
}
