/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ControladorPrincipal;

/**
 *
 * @author ramir
 */
public class GUILaberinto extends javax.swing.JFrame {

    /**
     * Creates new form GUILaberinto
     */
    public GUILaberinto(ControladorPrincipal controlador) {
        initComponents();
        escucharVolver(controlador);
        setVisible(true);
    }
    
    public void escucharVolver(ControladorPrincipal controlador){
       btnVolver.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiempo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        laberinto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tiempo.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tiempo.png"))); // NOI18N
        tiempo.setText("tiempo");
        getContentPane().add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 180, 60));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btnVolver.setText("btnVolver");
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 220, 50));

        laberinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laberinto.png"))); // NOI18N
        laberinto.setText("jLabel1");
        getContentPane().add(laberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 868, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel laberinto;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
