/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ramir
 */
//-----Imports-----
//--Controlador
import Controller.ControladorPrincipal;

//--Mouse Listener
import java.awt.event.MouseListener;

//-----codigo
public class GUILaberinto extends javax.swing.JFrame {
     private PanelLaberinto panelLaberinto; 

    /**
     * Creates new form GUILaberinto
     */
    public GUILaberinto(Controller.ControladorPrincipal controlador) {
        initComponents();
        
        //Para volver a guiPrincipal(menu)
        escucharVolver(controlador);
        
        //Hacer visible al GUILaberinto
        setVisible(true);
          
    }//fin metodo GUILaberinto
    
    public PanelLaberinto getPanelLaberinto(){
        return panelLaberinto;
    }//fin getPanelLaberinto
    
     public void escuchar(MouseListener controlador){
         this.addMouseListener(controlador);
     }
    
    public void escucharVolver(ControladorPrincipal controlador){
       // Este método permite que al hacer clic en el botón, el usuario regrese a la pantalla principal
       btnVolver.addActionListener(controlador);
    }//fin escucharVolver
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLaberinto2 = new view.PanelLaberinto();
        tiempo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        laberinto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLaberinto2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelLaberinto2.setAlignmentX(0.0F);
        panelLaberinto2.setAlignmentY(0.0F);
        panelLaberinto2.setEnabled(false);

        javax.swing.GroupLayout panelLaberinto2Layout = new javax.swing.GroupLayout(panelLaberinto2);
        panelLaberinto2.setLayout(panelLaberinto2Layout);
        panelLaberinto2Layout.setHorizontalGroup(
            panelLaberinto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        panelLaberinto2Layout.setVerticalGroup(
            panelLaberinto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        getContentPane().add(panelLaberinto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 560, 450));

        tiempo.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tiempo.png"))); // NOI18N
        tiempo.setText("tiempo");
        getContentPane().add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 180, 60));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btnVolver.setText("btnVolver");
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 220, 50));

        laberinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laberinto-fondo.png"))); // NOI18N
        laberinto.setText("jLabel1");
        getContentPane().add(laberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 868, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel laberinto;
    private view.PanelLaberinto panelLaberinto2;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
