/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ControladorPrincipal;

/**
 *
 * @author ramir
 */
public class GUIWin extends javax.swing.JFrame {

    /**
     * Creates new form JuegoGanado
     */
    public GUIWin(Controller.ControladorPrincipal controlador) {
        initComponents();
        
         setLocationRelativeTo(null); // Centrar la ventana en la pantalla
         
          setVisible(false);
    }
     
    public void mostrar() {
        setVisible(true); // Mostrar la ventana
    }

    public void aMenu(ControladorPrincipal controlador){
       btnAMenu.addActionListener(controlador);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAMenu = new javax.swing.JButton();
        win = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(370, 361));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAMenu.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        btnAMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnAMenu.setText("btnAMenu");
        btnAMenu.setContentAreaFilled(false);
        btnAMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnAMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 190, -1));

        win.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        win.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/win.png"))); // NOI18N
        win.setText("jLabel1");
        win.setMaximumSize(new java.awt.Dimension(946, 664));
        win.setMinimumSize(new java.awt.Dimension(946, 664));
        win.setPreferredSize(new java.awt.Dimension(946, 664));
        getContentPane().add(win, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 870, 680));
        win.getAccessibleContext().setAccessibleName("win");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAMenu;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
