/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ramir
 */

//imports
import Controller.ControladorLaberinto;
import java.awt.Graphics;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

//codigo
public class PanelLaberinto extends javax.swing.JPanel {
    private ImageIcon areaLaberinto;
    private ControladorLaberinto controladorLaberinto;

    /**
     * Creates new form PanelLaberinto
     */
    public PanelLaberinto() {
        initComponents();
        
        //Este metodo crea el espacio para subir la imagen de la parte juagable del laberinto 
        areaLaberinto = new ImageIcon("./src/main/resources/img/areaJuego.png");
        
        //Para que no aparezca el fondo se puso opaque false en la parte de design aunque tambien se pudo haber puesto setOpaque en el source
    }//fin metodo constructor sin parametros

    public void setControlador(ControladorLaberinto controladorLaberinto){
       this.controladorLaberinto=controladorLaberinto;
   }
    
    public void paint(Graphics g){
        super.paint(g);
        areaLaberinto.paintIcon(this, g, 0, 0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
